### ISSUE TITLE
SHORT_COMMIT is empty when use disable default-features

### ISSUE THREAD

**Issue by baoyachi** [baoyachi/shadow-rs#164]
list const empty:
- [x] SHORT_COMMIT
- [x] COMMIT_AUTHOR
- [x] COMMIT_DATE
- [x] COMMIT_DATE_2822
- [x] COMMIT_DATE_3339
- [x] COMMIT_EMAIL
- [x] COMMIT_HASH
- [x] LAST_TAG

* cargo dep
```toml
[build-dependencies]
shadow-rs = { version = "0.25.0", default-features = false, features = ["tzdb"] }
```
