### ISSUE TITLE
How to use the Git info in a wasm application?

### ISSUE THREAD

**Issue by EnderNon** [baoyachi/shadow-rs#208]
I don't have a clue what is actually happening in the example wasm cargo.toml, but it doesn't seem to work with my application that builds using Trunk if I omit the default-features flag in `cargo.toml`.

So this compiles using `trunk serve`:

```
[package]
name = "idmangler-gui"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
idmangler-lib = "0.5.1"
sycamore = { version = "0.9.1", features = ["web", "futures", "hydrate", "serde", "suspense"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.138"
reqwasm = "0.5.0"
shadow-rs = { version="0.38.1", default-features = false, features = ["tzdb"] }

[build-dependencies]
shadow-rs = "0.38.1"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(sycamore_force_ssr)'] }

[package.metadata.wasm-pack.profile-release]
wasm-opt = false```


By removing default-features (then allowing the git feature), there's some long error that gets printed when using trunk serve.

My repo for this is at https://git.frfrnocap.men/idmangler/idmangler-gui , use `trunk serve` to see the error

**Comment by baoyachi** [comment]
Please try this:
```toml
[package]
name = "idmangler-gui"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
idmangler-lib = "0.5.1"
sycamore = { version = "0.9.1", features = ["web", "futures", "hydrate", "serde", "suspense"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.138"
reqwasm = "0.5.0"
shadow-rs = { version="0.38.1", default-features = false, features = ["tzdb"] }

[build-dependencies]
shadow-rs = { version="0.38.1", default-features = false, features = ["tzdb"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(sycamore_force_ssr)'] }

[package.metadata.wasm-pack.profile-release]
wasm-opt = false
```
